# Generated by Django 5.0.6 on 2025-02-15 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=200)),
                ('isbnnum', models.CharField(max_length=200, unique=True)),
                ('price', models.CharField(max_length=200)),
                ('bookimage', models.ImageField(blank=True, null=True, upload_to='book_img/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isIssued', models.CharField(default=None, max_length=50)),
                ('catid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryApp.category')),
            ],
        ),
    ]
