# Generated by Django 5.0.6 on 2025-02-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0003_book_auther'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookimage',
            field=models.ImageField(default=None, upload_to='book_img/'),
        ),
    ]
