# Generated by Django 5.0.6 on 2025-02-15 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0006_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mobilenumber',
            new_name='email',
        ),
    ]
