# Generated by Django 5.0.6 on 2025-02-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0007_rename_mobilenumber_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookimage',
            field=models.ImageField(upload_to='staitc/book_img/'),
        ),
    ]
