# Generated by Django 5.0.6 on 2025-02-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0009_alter_book_bookimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookimage',
            field=models.ImageField(upload_to='book_img/'),
        ),
    ]
