# Generated by Django 5.0.6 on 2025-02-17 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0011_alter_book_bookimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issuedbookdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(auto_now=True)),
                ('return_status', models.CharField(max_length=50)),
                ('fine', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryApp.book')),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryApp.student')),
            ],
        ),
    ]
