# Generated by Django 5.0.6 on 2025-02-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0012_issuedbookdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbookdetails',
            name='issued_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='issuedbookdetails',
            name='return_date',
            field=models.DateTimeField(),
        ),
    ]
