# Generated by Django 5.0.6 on 2025-02-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0013_alter_issuedbookdetails_issued_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbookdetails',
            name='issued_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='issuedbookdetails',
            name='return_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
