# Generated by Django 5.0.6 on 2025-02-17 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0014_alter_issuedbookdetails_issued_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbookdetails',
            name='issued_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 17, 22, 10, 957169)),
        ),
    ]
