# Generated by Django 5.0.6 on 2025-02-17 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0017_alter_issuedbookdetails_issued_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 18, 48, 44, 252222)),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 18, 48, 44, 252222)),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 18, 48, 44, 252222)),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 18, 48, 44, 252222)),
        ),
        migrations.AlterField(
            model_name='issuedbookdetails',
            name='issued_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 18, 48, 44, 253219)),
        ),
        migrations.AlterField(
            model_name='issuedbookdetails',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 18, 48, 44, 253219)),
        ),
        migrations.AlterField(
            model_name='student',
            name='regdate_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 18, 48, 44, 253219)),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 18, 48, 44, 253219)),
        ),
    ]
