# Generated by Django 5.0.6 on 2025-02-25 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0018_alter_book_created_at_alter_book_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 14, 26, 37, 588106)),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 14, 26, 37, 588106)),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 14, 26, 37, 586095)),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 14, 26, 37, 586095)),
        ),
        migrations.AlterField(
            model_name='issuedbookdetails',
            name='issued_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 14, 26, 37, 588106)),
        ),
        migrations.AlterField(
            model_name='issuedbookdetails',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 14, 26, 37, 588106)),
        ),
        migrations.AlterField(
            model_name='student',
            name='regdate_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 14, 26, 37, 588106)),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 14, 26, 37, 588106)),
        ),
    ]
