# Generated by Django 5.0.6 on 2025-02-25 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0020_alter_book_created_at_alter_book_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 19, 2, 48, 440807)),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 19, 2, 48, 440807)),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 19, 2, 48, 440807)),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 19, 2, 48, 440807)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='issuedbookdetails',
            name='issued_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 19, 2, 48, 440807)),
        ),
        migrations.AlterField(
            model_name='issuedbookdetails',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 19, 2, 48, 440807)),
        ),
        migrations.AlterField(
            model_name='student',
            name='regdate_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 19, 2, 48, 440807)),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 19, 2, 48, 440807)),
        ),
    ]
