# Generated by Django 5.0.6 on 2025-02-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0023_alter_book_created_at_alter_book_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
