# Generated by Django 5.0.6 on 2025-03-03 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0025_alter_issuedbookdetails_issued_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbookdetails',
            name='issued_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='issuedbookdetails',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
