# Generated by Django 5.0.6 on 2025-03-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0026_alter_issuedbookdetails_issued_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbookdetails',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
