# Generated by Django 5.0.6 on 2025-03-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0027_alter_issuedbookdetails_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbookdetails',
            name='return_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
