# Generated by Django 5.0.6 on 2025-03-05 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0035_alter_issuedbookdetails_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbookdetails',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 5, 8, 57, 5, 254597, tzinfo=datetime.timezone.utc)),
        ),
    ]
