# Generated by Django 5.0.6 on 2025-03-05 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0037_alter_issuedbookdetails_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbookdetails',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 5, 9, 5, 23, 778416, tzinfo=datetime.timezone.utc)),
        ),
    ]
