# Generated by Django 5.0.6 on 2025-03-05 09:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0039_alter_issuedbookdetails_issued_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbookdetails',
            name='issued_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
