# Generated by Django 5.0.6 on 2025-03-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0042_alter_issuedbookdetails_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
