# Generated by Django 5.0.6 on 2025-03-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0044_alter_book_created_at_alter_category_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='expire_at',
            field=models.DateField(default=None),
        ),
    ]
