# Generated by Django 5.0.6 on 2025-03-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0045_category_expire_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='expire_at',
        ),
        migrations.AddField(
            model_name='issuedbookdetails',
            name='expire_at',
            field=models.DateField(default=None),
        ),
    ]
