# Generated by Django 5.0.6 on 2025-03-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0046_remove_category_expire_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedbookdetails',
            name='expire_at',
        ),
    ]
