# Generated by Django 5.0.6 on 2025-03-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0047_remove_issuedbookdetails_expire_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='expire_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
