# Generated by Django 5.0.6 on 2025-03-19 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0048_category_expire_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='expire_at',
        ),
    ]
