# Generated by Django 5.0.6 on 2025-03-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0049_remove_category_expire_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedbookdetails',
            name='expire_at',
            field=models.DateField(blank=True, default=None),
        ),
    ]
