# Generated by Django 5.0.6 on 2025-03-19 18:48

import libraryApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0050_issuedbookdetails_expire_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbookdetails',
            name='expire_at',
            field=models.DateField(blank=True, default=None, verbose_name=libraryApp.models.Book),
        ),
    ]
