# Generated by Django 5.0.6 on 2025-03-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0051_alter_issuedbookdetails_expire_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedbookdetails',
            name='expire_at',
        ),
        migrations.AddField(
            model_name='book',
            name='expire_at',
            field=models.DateField(blank=True, default=None),
        ),
    ]
