# Generated by Django 5.0.6 on 2025-03-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0052_remove_issuedbookdetails_expire_at_book_expire_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='expire_at',
            field=models.DateField(default=None, null=True),
        ),
    ]
